name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"   # roda 1x por dia
  workflow_dispatch:       # permite rodar manualmente
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: CrisleiKeliJenuino
          outputs: dist/snake.svg
          theme: dark          # quadradinhos verdes sobre fundo escuro
          color: "00F779"      # cor do rastro da cobra (neon verde)
          background: "0D1117" # fundo do SVG escuro

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
